version: "3"
services:
  back:
    build: ./Back
    environment:
        HOST: db
        DB_NAME: "postgres"
        PSQL_USER: postgres
        PSQL_PASS: postgres
        DB_HOST: db
    ports:
      - 3000:3000
    links:
      - db
  db:
    image: postgres:latest
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
  client:
    build: ./Front
    ports:
      - 8080:8080